- hosts: localhost
  become: no
  vars:
    openshift_token: openshift-token
    domain: example.com
    postgres_password: 'changeme'
    storeid: TOKYO
    openshift_url: "https://api.{{ domain }}:6443"
    project_namespace: quarkuscoffeeshop-demo
    delete_deployment: false
    insecure_skip_tls_verify: true
    default_owner: root
    default_group: root
    skip_amq_install: false
    skip_configure_postgres: false
    skip_mongodb_operator_install: true
    single_mongodb_install: false 
    skip_quarkuscoffeeshop_helm_install: true
  roles:
  - quarkuscoffeeshop-ansible
