- name: Create new project for quarkus-robotshop
  command: "{{ oc_location }}  new-project {{ project_namespace }}"
  register: create_project_result
  ignore_errors: yes
  when: not delete_deployment|bool

- name: Switch to project for  quarkus-robotshop
  command:  "{{ oc_location }}  project {{ project_namespace }}"
  when: not delete_deployment|bool